---
#check rescue mode
- name: check rescue mode
  shell: grep "Hetzner Rescue System" /etc/motd
  register: rescue_mode
  failed_when: false

#display msg if false
- name: ensure rescue mode
  fail:
    msg: System not in RESCUE mode
  when: rescue_mode.rc != 0

#read info about partitions
- name: read info about partitions
  parted:
    device: "{{ item }}"
    unit: MiB
  register: info
  with_items:
    - /dev/sda
    - /dev/sdb 
    - /dev/sdc
    - /dev/sdd

#remove all lg, lv
- name: remove LVM
  shell: "dmsetup remove_all"

#remove all RAID arrays
- name: remove raid arrays
  shell: "mdadm --stop /dev/md*"

#delete partitions which we read and saved earlier
- name: delete partitions
  parted: 
    device: "{{ item.0.disk.dev }}"
    number: "{{ item.1.num }}"
    state: absent
    loop: "{{ info.results|subelements('partitions') }}"

#generate cfg file for installimage
- name: generate installimage.conf
  template: >
    src={{ item }}.j2
    dest=/{{ item }}
    mode=0600
    force=yes
  with_items:
    - "installimage.conf"

#install system through installimage
- name: install system
  shell: /root/.oldroot/nfs/install/installimage -a -c /installimage.conf

- name: reboot system
  reboot:
    reboot_timeout: 300

- name: update packages
  raw: apt-get update

- name: install python
  raw: apt-get -y install python3 python3-pip python3-dev python3-virtualenv


